build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USERNAME/drone-ansible
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/drone-ansible
    tag: develop
    when:
      branch: develop

# plugin:
#   name: Docker
#   desc: Build and Publish images to a Docker registry.
#   type: publish
#   image: plugins/drone-docker
#   labels:
#     - docker
#     - image
#     - container
